### ISSUE TITLE
Can the recorded actions e.g. reference document also be shared?

### ISSUE THREAD

**Issue by SiyuanHuang95** [mnotgod96/AppAgent#10]
Hi, thanks for sharing.

I am wondering whether you could also share the reference document since it's expensive to use the GPT4V API to construct such a document. In such a way, the community could focus more on the Agent usage.

**Comment by icoz69** [comment]
hi, currently the doc is device-specific due to the design of unique ID of elements. You may try our project with an easy task, which would not cost a lot.

**Comment by SiyuanHuang95** [comment]
Ok. Thanks for the update and info.
