### ISSUE TITLE
Question regarding XML feeding to the LLM

### ISSUE THREAD

**Issue by Garry101CN** [mnotgod96/AppAgent#17]
Hi team,

I am impressed about your research. Thank you for providing such a meaningful direction towards AI. While reading through your research, I was confused about your mentioned XML file that is fed to the model as an input. If I understand correctly, such XML should supply the details of the layout of an UI page. You mentioned that a unique identifier is given to any UI element by its Resource ID(if given) or its metadata. Resource ID is also used as an identifier in Android development, particularly in an XML file. So I think that the XML you mentioned here is the same one in Android dev. What's weired is that no location info of a UI element is given through an Android XML file. I refered to your code and found that you used ET lib to travel the XML file, and found that the location info is extracted through a property named "bounds" in the XML file, in the form of "[x1,y1][x2,y2]". This sets off my confusion cuz to my knowledge there's no such property in Android XML file.

Could you please correct me if I missunderstand the XML file here? Or can you further introduce how this XML is generated?
Thank you and congrats on your great work!

Best,
Gary

**Comment by mnotgod96** [comment]
If you take a close look at the and_controller.py in the scripts directory, the xml file is dumped using the uiautomator. The bounds property can be found in the xml file for every element in the UI hierarchy.

**Comment by Garry101CN** [comment]
Yes, I got it after a closer reading. Thank you for help!
