### ISSUE TITLE
while running 2. human demonstration

### ISSUE THREAD

**Issue by sesuii** [mnotgod96/AppAgent#19]
When I running human demonstration phase, I could only see half of the labeled screenshots, as shown in the picture below, and this window could not be changed in size or moved up and down.
So I can't know the UI element number in the lower half of the screen unless I actively open the apps/appname/demos folder.

<img width="960" alt="992a3d884b037da5f87b07b8e7e5ff5d" src="https://github.com/mnotgod96/AppAgent/assets/72365241/5ae65f36-97d0-4cf6-88d9-ff524b774753">

**Comment by XindongHao** [comment]
You  can search labeled_screenshots dir in apps directory

**Comment by sesuii** [comment]
> You can search labeled_screenshots dir in apps directory

I did it this way, but isn't the pop-up window just for easier viewing of the UI numbers? Of cause it's a small user-experience issue that I just make sure you know.

**Comment by zhelloworld123456** [comment]
我也遇到同样的问题，image上的图片显示数字不全，我输入tap指令的时候，需要的操作数字看不到

**Comment by sesuii** [comment]
> 我也遇到同样的问题，image上的图片显示数字不全，我输入tap指令的时候，需要的操作数字看不到

是的，目前只能在文件夹中找到对应标记页面截图查看元素编号，再进行下一步操作。

**Comment by zhelloworld123456** [comment]
您好，我想咨询下哈，这个AppAgent支持通过脚本来操作指令吗？目前我有一个需求就是，打开高德地图，不断的输入打车的起始地点和打车的目的地位置，来获取打车的的路线和价格信息。这种可以通过脚本来实现这个操作吗
















在 2024-03-14 11:42:28，"songjah" ***@***.***> 写道：

我也遇到同样的问题，image上的图片显示数字不全，我输入tap指令的时候，需要的操作数字看不到

是的，目前只能在文件夹中找到对应标记页面截图查看元素编号，再进行下一步操作。

**Comment by sesuii** [comment]
您可以尝试先拆分指令再下达给 AppAgent。在我上一次使用 AppAgent 时，发现它对中文效果不太好，当然这和使用的模型 gpt-4v 有关(
https://www.robertmao.com/comments/blog/zh/chat-gpt-4-v-first-time-expereince)
，我不清楚现在是否有优化。另外，您需要考虑该需求的成本开销。

zhelloworld123456 ***@***.***> 于2024年3月14日周四 19:56写道：
