### ISSUE TITLE
执行adb -s pull命令时报错

### ISSUE THREAD

**Issue by sukekes** [mnotgod96/AppAgent#23]
【环境说明】
操作系统：Win11
Anaconda版本：23.7.2
内部python版本：3.11
Android设备：Pixel 6 Pro API 31（模拟器）

【操作步骤】
1. 根据步骤运行appgent，执行python ./learn.py
2. modes选择2
3. app输入Gmail
4. 内容输入“send an email to Jane”

【实际结果】
出现错误如下：Command execution failed: adb -s emulator-5554 pull /sdcard/demo_Gmail_2024-01-04_17-20-09_1.xml ./apps\Gmail\demos\demo_Gmail_2024-01-04_17-20-09\xml\demo_Gmail_2024-01-04_17-20-09_1.xml

【错误截图】
![image](https://github.com/mnotgod96/AppAgent/assets/38717537/67761666-9380-4785-9b52-d3cd533499e8)

**Comment by nateshmbhat** [comment]
Same error happening

**Comment by mnotgod96** [comment]
It is possible that your emulator does not have a path called /sdcard/..., you can open the device explorer of your emulator to see where you can store the intermediate screenshots and xml files, and change ANDROID_SCREENSHOT_DIR and ANDROID_XML_DIR in the config.yaml file.
![2 ODS84V0$039JJJIW%F$L](https://github.com/mnotgod96/AppAgent/assets/27103154/97081d90-1765-468e-9e3c-463fce1a05b4)
