### ISSUE TITLE
Questions about the content of the task and the amount of documentation

### ISSUE THREAD

**Issue by kig1929** [mnotgod96/AppAgent#40]
I am interested in your research and thank you for sharing your project!
I have some questions about AppAgent.

1. Could you share a list of 50 tasks over 10 apps from the paper? I think it would be helpful for others to know the details of this study if the entire process was disclosed with the exception of the demo.
2. How many documents were generated for each task during the exploration phase? I want to know how much exploration is needed to be used meaningfully.

**Comment by icoz69** [comment]
hi, thanks for your interest. we are going to release a more comprehensive benchmark with more apps and tasks in the future. please look forward to it.

**Comment by kig1929** [comment]
Could you give me a rough estimate of when that might be?

**Comment by icoz69** [comment]
hi, we have updated the tasks we evaluated in : https://github.com/mnotgod96/AppAgent/blob/main/assets/testset.md

**Comment by kig1929** [comment]
Thanks for sharing:)
