### ISSUE TITLE
无法使用human demonstration模式

### ISSUE THREAD

**Issue by peng2219** [mnotgod96/AppAgent#48]
使用human demonstration模式，输入了 target app 和goal，显示手机截图，并且有以下提示
“All interactive elements on the screen are labeled with red and blue numeric tags. Elements labeled with red tags are clickable elements; elements labeled with blue tags are scrollable elements.”
之后，一直停在这里，不往下进行，请问如何处理？

**Comment by mnotgod96** [comment]
跳出截图窗口后点击键盘上任意一个键就可以在命令行继续输入了

**Comment by peng2219** [comment]
感谢， 也是有时 work，有时不 work
